version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - HOST=${HOST}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE=${DATABASE}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}

  backoffice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
